bank/bank/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('bbapp.urls')),
    path('credentials/', include('credentials.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

bank/bbapp/urls.py
from . import views
from django.urls import path,include
app_name='bbapp'
urlpatterns = [
    path('',views.index,name='index'),
    path('account/', views.account, name='account'),
    path('ajax/load-branches/',views.load_branches, name='ajax_load_branches'),
    path('success/', views.success, name='success'),
]

bank/credentials/urls.py
from django.urls import path,include
from . import views
app_name='credentials'
urlpatterns = [
    path('register',views.register,name='register'),
    path('login',views.login,name='login'),
    path('logout',views.logout,name='logout')

]

bank/bbapp/models.py
from django.db import models

# Create your models here.
class District(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    wiki = models.URLField()

    class Meta:
        ordering = ('name',)
        verbose_name = 'District'
        verbose_name_plural = 'Districts'

    def __str__(self):
        return self.name
class Gender(models.Model):
    name = models.CharField(max_length=200)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Gender'
        verbose_name_plural = 'Genders'

    def __str__(self):
        return self.name

class Branches(models.Model):
    name = models.CharField(max_length=200)
    district = models.ForeignKey(District, on_delete=models.CASCADE)
    slug = models.SlugField(unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Branch'
        verbose_name_plural = 'Branches'

    def __str__(self):
        return self.name

class CardPreference(models.Model):
    name = models.CharField(max_length=200)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Card'
        verbose_name_plural = 'cards'

    def __str__(self):
        return self.name
class AccountPreferance(models.Model):
    name = models.CharField(max_length=200)

    class Meta:
        ordering = ('name',)
        verbose_name = 'type'
        verbose_name_plural = 'types'

    def __str__(self):
        return self.name

class AccountDetails(models.Model):
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    dob = models.DateField()
    email = models.EmailField(unique=True)
    mobile_number = models.CharField(max_length=10)
    address_line_1 = models.CharField(max_length=250)
    gender = models.ForeignKey(Gender, on_delete=models.SET_NULL, null=True)
    type = models.ForeignKey(AccountPreferance, on_delete=models.SET_NULL, null=True)
    district = models.ForeignKey(District, on_delete=models.SET_NULL, null=True)
    branch = models.ForeignKey(Branches, on_delete=models.SET_NULL, null=True)
    card = models.ForeignKey(CardPreference, on_delete=models.SET_NULL, null=True)

    class Meta:
        ordering = ('first_name',)
        verbose_name = 'AccountDetail'
        verbose_name_plural = 'AccountDetails'

    def __str__(self):
        return self.first_name

bank/credentials/models.py
from django.db import models

# Create your models here.

bank/bbapp/forms.py
from django import forms
from .models import Branches,AccountDetails


class AccountForm(forms.ModelForm):

    class Meta:
        model = AccountDetails
        fields = (
            'first_name',
            'last_name',
            'dob',
            'email',
            'mobile_number',
            'address_line_1',
            'gender',
            'type',
            'district',
            'branch',
            'card',
                  )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)          #super implementation os init method
        self.fields['branch'].queryset = Branches.objects.none() #quersyset responsible for showing all the sub branch

        if 'district' in self.data:
            try:
                district_id = int(self.data.get('district'))
                self.fields['branch'].queryset = Branches.objects.filter(district_id=district_id).order_by('name')
            except (ValueError, TypeError):
                pass
        elif self.instance.pk:
            self.fields['branch'].queryset = self.instance.district.branch_set.order_by('name')

bank/bbapp/views.py
from django.shortcuts import render, redirect
from .models import Branches,District
from .forms import AccountForm
from django.http import JsonResponse

# Create your views here.
def index(request):
    district=District.objects.all()
    return render(request,'index.html',{'districts':district})
def account(request):
    if request.method == 'POST':
        form = AccountForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('bbapp:success')
    else:
        form = AccountForm()
    return render(request, 'account.html', {'form': form})
def load_branches(request):
    district_id = request.GET.get('district_id')  #district id is from ajax requsest for data
    branches = Branches.objects.filter(district_id=district_id).order_by('name')
    return render(request,'branch_dropdown_list_options.html',{'branches':branches})
def success(request):
    return render(request, 'success.html')

bank/credentials/views.py
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.shortcuts import render, redirect


# Create your views here.
def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username,password=password)
        if user is not None:
            auth.login(request,user)
            return redirect('/')
        else:
            messages.info(request,'credentials invalid')
            return redirect('login')
    return render(request,'login.html')
def register(request):
    if request.method == 'POST':
        username = request.POST['username']
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        email = request.POST['email']
        password = request.POST['password']
        cpassword = request.POST['password2']
        if cpassword== password:
            if User.objects.filter(username=username).exists():
                messages.info(request,'username taken')
                return redirect('register')
            elif User.objects.filter(email=email).exists():
                messages.info(request,'email taken')
                return redirect('register')
            else:
                user = User.objects.create_user(username=username,password=password,first_name=first_name,last_name=last_name,email=email)
                user.save()
                messages.info(request,'user created')
                return redirect('login')
        else:
            messages.info(request,'password not matched')
            return redirect(request,'register')
    return render(request,'register.html')
def logout(request):
    auth.logout(request)
    return redirect('/')

bank/templates/account.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

<link rel="icon" type="image/png" href="{% static 'images/icons/favicon.ico' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/Linearicons-Free-v1.0.0/icon-font.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animsition/css/animsition.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/daterangepicker/daterangepicker.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>
<body>
<div class="limiter">
		<div class="container-login100" style="background-image: url('{% static 'images/bg-01.jpg' %}');">
			<div class="wrap-login100 p-t-30 p-b-50">
                <span class="login100-form-title p-b-41">
					Account Registration
				</span>
<form  class="login100-form validate-form" id="account_form" data-branches-url="{% url 'bbapp:ajax_load_branches' %}"  method="post" >
    {% csrf_token %}

	<label class="text-dark ">First Name</label>{{form.first_name}}<br>
	<label class="text-dark">last_name</label>{{form.last_name}}<br>
	<label class="text-dark">address_line</label>{{form.address_line_1}}<br>
	<label class="text-dark">dob(dd/mm/yyyy)</label>{{form.dob}}<br>
	<label class="text-dark">email</label>{{form.email}}<br>
	<label class="text-dark">mobile_number</label>{{form.mobile_number}}<br>
	<label class="text-dark">gender</label>{{form.gender}}<br>
	<label class="text-dark">type of account</label>{{form.type}}<br>
	<label class="text-dark">district</label>{{form.district}}<br>
	<label class="text-dark">branch</label>{{form.branch}}<br>
	<label class="text-dark">card</label>{{form.card}}<br>
    <input class="login100-form-btn" type="submit">
	<button class="login100-form-btn" href="{% url 'bbapp:index' %}">cancel</button>
</form>
            </div>
        </div>
    </div>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_district").change(function () {
      var url = $("#account_form").attr("data-branches-url");   //fetching url from forms
      var districtId = $(this).val();    //getting selected district id

      $.ajax({
        url: url,
        data: {
          'district_id': districtId             //adding district id to get data
        },
        success: function(data) {
          console.log(data);
          $("#id_branch").html(data);
        }
      });

    });

</script>
</body>
</html>

bank/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
   <head>
      <!-- basic -->
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <!-- mobile metas -->
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="viewport" content="initial-scale=1, maximum-scale=1">
      <!-- site metas -->
      <title>bank</title>
      <meta name="keywords" content="">
      <meta name="author" content="">
      <meta content="{% block metadescription %}{% endblock %}" name="description">
      <!-- bootstrap css -->
      <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
      <!-- style css -->
      <link rel="stylesheet" href="{% static 'css/style.css' %}">
      <!-- Responsive-->
      <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
      <!-- fevicon -->
      <link rel="icon" href="{% static 'images/fevicon.png' %}" type="image/gif" />
      <!-- Scrollbar Custom CSS -->
      <link rel="stylesheet" href="{% static 'css/jquery.mCustomScrollbar.min.css' %}">
      <!-- Tweaks for older IEs-->
      <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js}"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js}"></script><![endif]-->
   </head>
   <!-- body -->
   <body class="main-layout">
      <!-- loader  -->
      <div class="loader_bg">
         <div class="loader"><img src="{% static 'images/loading.gif' %}" alt="" /></div>
      </div>
      <!-- end loader -->
      <!-- header -->
      <header>
         <!-- header inner -->
         <div class="container-fluid">
            <div class="row">
               <div class="col-lg-12">
                  <div class="menu-area">
                     <div class="limit-box">
                        <nav class="main-menu">
                           <ul class="menu-area-main">
                              <li class="active">
                                 <a href="">Home</a>
                              </li>
                              <li>
                                 <button  class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Districts</button>
                                     <div class="dropdown-menu" aria-labelledby="dropdownMenuButton" >
                                          {% for district in district_objects %}
                                            <a class="dropdown-item" href="{{district.wiki}}">{{district.name}}</a>
                                          {% endfor %}
                                     </div>
                              </li>

                              {% if user.is_authenticated %}
									<li>{{user.username}}</li>
									<li><a href="credentials/logout">logout</a></li>
                              {% else %}
									<li><a href="credentials/register">register</a></li>
									<li><a href="credentials/login">login</a></li>
                              {% endif %}
                              <li>
                                 <a href="#"><img src="{% static 'images/search_icon.png' %}" alt="#" /></a>
                              </li>
                           </ul>
                        </nav>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         <!-- end header inner -->
      </header>
      <!-- end header -->


{% block body %}


{% endblock %}
   <!-- footer -->
      <div class="cpy">
         <div class="container">
            <div class="row">
               <div class="col-md-12">
                  <p>Copyright © <a href="">Sarath Krishna K</a></p>
               </div>
            </div>
         </div>
      </div>
      <!-- end footer -->
      <!-- Javascript files-->
      <script src="{% static 'js/jquery.min.js' %}"></script>
      <script src="{% static 'js/popper.min.js' %}"></script>
      <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
      <script src="{% static 'js/jquery-3.0.0.min.js' %}"></script>
      <script src="{% static 'js/plugin.js' %}"></script>
      <!-- Scrollbar Js Files -->
      <script src="{% static 'js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
      <script src="{% static 'js/custom.js' %}"></script>
   </body>
</html>

bank/templates/branch_dropdown_list_options.html
<option >Select your center</option>
{% for branch in branches %}
<option value="{{ branch.pk }}">{{ branch.name }}</option>
{% endfor %}

bank/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block body %}

      <!-- revolution slider -->

      <!-- end revolution slider -->
      <!-- section --> 
      <div class="section layout_padding">
         <div class="container">
            <div class="row">
               <div class="col-md-12">
                  <div class="heading">
                     <h3>New</h3><br>
                      <h3><span class="orange_color">account</span></h3>
                  </div>
               </div>
            </div>


            <div class="row margin_top_30">
               <div class="col-md-12">
                  <div class="button_section full center margin_top_30">
                     <a style="margin:0;" href="{% if user.is_authenticated %}{% url 'bbapp:account' %}{% else %}{% url 'credentials:login' %}{% endif %}">Apply</a>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <!-- end section -->
      <!-- section -->

      <!-- end section -->
      <!-- section --> 
      <div class="section layout_padding">
         <div class="container">

         </div>
      </div>
      <!-- end section -->
{% endblock %}

bank/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Login V16</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="{% static 'images/icons/favicon.ico' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/Linearicons-Free-v1.0.0/icon-font.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animsition/css/animsition.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/daterangepicker/daterangepicker.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
<!--===============================================================================================-->
</head>
<body>

	<div class="limiter">
		<div class="container-login100" style="background-image: url('{% static 'images/bg-01.jpg' %}');">
			<div class="wrap-login100 p-t-30 p-b-50">
				<span class="login100-form-title p-b-41">
					Account Login
				</span>
				<form class="login100-form validate-form p-b-33 p-t-5" action="login" method="post">
					{% csrf_token %}

					<div class="wrap-input100 validate-input" data-validate = "Enter username">
						<input class="input100" type="text" name="username" placeholder="User name">
						<span class="focus-input100" data-placeholder="&#xe82a;"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate="Enter password">
						<input class="input100" type="password" name="password" placeholder="Password">
						<span class="focus-input100" data-placeholder="&#xe80f;"></span>
					</div>

					<div class="container-login100-form-btn m-t-32">
						<button class="login100-form-btn">
							Login
						</button>
					</div>

				</form>
			</div>
		</div>
	</div>

	{% for i in messages %}
    <h2>{{i}}</h2>
     {% endfor %}


	<div id="dropDownSelect1"></div>

<!--===============================================================================================-->
	<script src="{% static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/animsition/js/animsition.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/daterangepicker/moment.min.js' %}"></script>
	<script src="{% static 'vendor/daterangepicker/daterangepicker.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/countdowntime/countdowntime.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'js/main.js' %}"></script>

</body>
</html>

bank/templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="icon" type="image/png" href="{% static 'images/icons/favicon.ico' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/Linearicons-Free-v1.0.0/icon-font.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animsition/css/animsition.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/daterangepicker/daterangepicker.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <title>Title</title>
</head>
<body>
<div class="limiter">
		<div class="container-login100" style="background-image: url('{% static 'images/bg-01.jpg' %}');">
			<div class="wrap-login100 p-t-30 p-b-50">
                <span class="login100-form-title p-b-41">
					Account Registration
				</span>
<form action="register" method="post" class="login100-form validate-form">
    {% csrf_token %}
    <input class="input100" type="text" name="username" placeholder="username"><br>
    <input class="input100" type="text" name="first_name" placeholder="enter your name"><br>
    <input class="input100" type="text" name="last_name" placeholder="enter your last name"><br>
    <input class="input100" type="email" name="email" placeholder="enter your email"><br>
    <input class="input100" type="password" name="password" placeholder="enter your password "><br>
    <input class="input100" type="password" name="password2" placeholder="confirm password"><br>
    <input class="login100-form-btn" type="submit">
</form>
            </div>
        </div>
</div>
{% for msg in messages %}
<h2>{{msg}}</h2>
{% endfor %}
</body>
</html>

bank/templates/success.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<div class="section layout_padding">
         <div class="container">
            <div class="row">
               <div class="col-md-12">
                  <div class="heading">
                     <h3>Account</h3><br>
                     <h3><span class="orange_color"><br>created</span></h3>
                  </div>
               </div>
            </div>


            <div class="row margin_top_30">
               <div class="col-md-12">
                  <div class="button_section full center margin_top_30">
                     <a style="margin:0;" href="{% url 'bbapp:index' %}">Home</a>
                  </div>
               </div>
            </div>
         </div>
      </div>
{% endblock %}